#!/usr/bin/env bash

INPUTFILELOCATION=$1
OUTPUTFILELOCATION=$2
BADFILELOCATION=$3
INPUTFILENAME=$4
PASSWORD=$5

sbt "run \"${INPUTFILELOCATION}\" \"${OUTPUTFILELOCATION}\" \"${BADFILELOCATION}\" \"${INPUTFILENAME}\" \"${PASSWORD}\""